### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by eliasdefrancisco** [atSistemas/techday-6#1]
Hello, this is my log when I do  # mvn clean install

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.818s
[INFO] Finished at: Wed Apr 19 09:11:39 CEST 2017
[INFO] Final Memory: 16M/176M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wpaas-example: Could not resolve dependencies for project com.atsistemas.techday:wpaas-example:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.11, org.springframework:spring-beans:jar:4.3.7.RELEASE, org.springframework:spring-webmvc:jar:4.3.7.RELEASE, junit:junit:jar:4.12, org.assertj:assertj-core:jar:2.6.0, org.mockito:mockito-core:jar:1.10.19, org.springframework:spring-core:jar:4.3.7.RELEASE, org.springframework:spring-test:jar:4.3.7.RELEASE: Could not transfer artifact org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.11 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/apache/tomcat/embed/tomcat-embed-core/8.5.11/tomcat-embed-core-8.5.11.jar from central failed: No space left on device -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by cmcornejocrespo** [comment]
Hola Elias,
sigues teniendo el problema?
Veo en el log ---  No space left on device, podrías comprobar que tienes suficiente espacio en el disco?

Un saludo!
Carlos M.

**Comment by eliasdefrancisco** [comment]
Buenas Carlos, primer error solucionado, maldita máquina virtual!
Pero sigue lanzandome un BUIL FAILURE, esta vez el log dice esto, si quieres te lo creo en una nueva issue

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.138s
[INFO] Finished at: Thu Apr 20 10:42:36 CEST 2017
[INFO] Final Memory: 14M/174M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project wpaas-example: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException


Puede que esté pidiendo java 1.8?
un saludo!

**Comment by cmcornejocrespo** [comment]
Hola,

Efectivamente necesitas java 8

Nos vas contando.

Gracias,
Carlos M.

**Comment by drhelius** [comment]
Pues en los requisitos que se enviaron pusimos Java 7 :no_mouth:

**Comment by cmcornejocrespo** [comment]
Lo siento...

Kind regards,
Carlos M.
